version: '3'

services:
    
   my-registry:
     container_name: ${CONTAINER_REGISTRY_NAME}
     image: registry:${REGISTRY_VERSION:-latest}
     restart: unless-stopped
     volumes:
       - ${REGISTRY_FILES_PATH}:/var/lib/registry
       - ${CERTIFICATE_PATH}:/certs
       - ${REGISTRY_AUTH_PATH}:/auth/
     environment:
       VIRTUAL_PORT: 5000
       REGISTRY_HTTP_ADDR: ${PUBLIC_IP_ADDRESS}:443
       REGISTRY_HTTP_TLS_CERTIFICATE: ${REGISTRY_SSL_CERTIFICATE}
       REGISTRY_HTTP_TLS_KEY: ${REGISTRY_SSL_KEY}
       REGISTRY_AUTH: htpasswd
       REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
       REGISTRY_AUTH_HTPASSWD_PATH: ${REGISTRY_AUTH_HTPASSWD_PATH}
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
     logging:
       options:
         max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}

networks:
    default:
       external:
         name: ${NETWORK}
